// ── Tous les versets (rotation automatique globale) ─────────────────────────

export const DAILY_VERSES = [
  // Salut & Grâce
  {text:"Car Dieu a tant aimé le monde qu'il a donné son Fils unique, afin que quiconque croit en lui ne périsse point, mais qu'il ait la vie éternelle.",ref:"Jean 3:16"},
  {text:"C'est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c'est le don de Dieu.",ref:"Éphésiens 2:8"},
  {text:"Si tu confesses de ta bouche le Seigneur Jésus, et si tu crois dans ton cœur que Dieu l'a ressuscité des morts, tu seras sauvé.",ref:"Romains 10:9"},
  {text:"Car le salaire du péché, c'est la mort ; mais le don gratuit de Dieu, c'est la vie éternelle en Jésus-Christ notre Seigneur.",ref:"Romains 6:23"},
  {text:"Il n'y a de salut en aucun autre ; car il n'y a sous le ciel aucun autre nom qui ait été donné parmi les hommes, par lequel nous devions être sauvés.",ref:"Actes 4:12"},
  {text:"Il nous a sauvés, non à cause des œuvres de justice que nous aurions faites, mais selon sa miséricorde, par le bain de la régénération et le renouvellement du Saint-Esprit.",ref:"Tite 3:5"},
  {text:"Si quelqu'un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées ; voici, toutes choses sont devenues nouvelles.",ref:"2 Corinthiens 5:17"},
  {text:"Mais Dieu prouve son amour envers nous, en ce que, lorsque nous étions encore des pécheurs, Christ est mort pour nous.",ref:"Romains 5:8"},
  {text:"Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner et pour nous purifier.",ref:"1 Jean 1:9"},
  {text:"Je suis le chemin, la vérité et la vie. Nul ne vient au Père que par moi.",ref:"Jean 14:6"},
  {text:"Voici, je me tiens à la porte, et je frappe. Si quelqu'un entend ma voix et ouvre la porte, j'entrerai chez lui, je souperai avec lui, et lui avec moi.",ref:"Apocalypse 3:20"},
  // Foi
  {text:"La foi est une ferme assurance des choses qu'on espère, une démonstration de celles qu'on ne voit pas.",ref:"Hébreux 11:1"},
  {text:"Or, sans la foi, il est impossible de lui être agréable ; car il faut que celui qui s'approche de Dieu croie que Dieu existe, et qu'il est le rémunérateur de ceux qui le cherchent.",ref:"Hébreux 11:6"},
  {text:"Ayez foi en Dieu. Je vous le dis en vérité, si quelqu'un dit à cette montagne : Ôte-toi de là et jette-toi dans la mer, et s'il ne doute pas dans son cœur, mais croit que ce qu'il dit arrivera, il le verra s'accomplir.",ref:"Marc 11:22-23"},
  {text:"Si vous aviez de la foi comme un grain de sénevé, vous diriez à cette montagne : Déplace-toi d'ici là, et elle se déplacerait ; rien ne vous serait impossible.",ref:"Matthieu 17:20"},
  {text:"Ainsi la foi vient de ce qu'on entend, et ce qu'on entend vient de la parole de Christ.",ref:"Romains 10:17"},
  {text:"Car nous marchons par la foi et non par la vue.",ref:"2 Corinthiens 5:7"},
  {text:"Ainsi la foi, si elle n'a pas les œuvres, est morte en elle-même.",ref:"Jacques 2:17"},
  {text:"Prenez par-dessus tout cela le bouclier de la foi, avec lequel vous pourrez éteindre tous les traits enflammés du malin.",ref:"Éphésiens 6:16"},
  {text:"Afin que l'épreuve de votre foi, plus précieuse que l'or périssable éprouvé par le feu, ait pour résultat la louange, la gloire et l'honneur, lorsque Jésus-Christ apparaîtra.",ref:"1 Pierre 1:7"},
  {text:"J'ai été crucifié avec Christ ; et si je vis, ce n'est plus moi qui vis, c'est Christ qui vit en moi.",ref:"Galates 2:20"},
  {text:"Tout est possible à celui qui croit.",ref:"Marc 9:23"},
  // Amour de Dieu
  {text:"Celui qui n'aime pas n'a pas connu Dieu, car Dieu est amour.",ref:"1 Jean 4:8"},
  {text:"Pour nous, nous l'aimons parce qu'il nous a aimés le premier.",ref:"1 Jean 4:19"},
  {text:"Car j'ai l'assurance que ni la mort, ni la vie, ni les anges, ni les dominations, ni les choses présentes, ni les choses à venir ne pourront nous séparer de l'amour de Dieu manifesté en Jésus-Christ notre Seigneur.",ref:"Romains 8:38-39"},
  {text:"Je t'ai aimé d'un amour éternel ; c'est pourquoi je te conserve ma grâce.",ref:"Jérémie 31:3"},
  {text:"L'Éternel, ton Dieu, est au milieu de toi, comme un héros qui sauve ; il fera de toi sa joie et son allégresse, il aura pour toi des transports de joie.",ref:"Sophonie 3:17"},
  {text:"Car autant les cieux sont élevés au-dessus de la terre, autant sa bonté est grande pour ceux qui le craignent ; autant l'orient est éloigné de l'occident, autant il éloigne de nous nos transgressions.",ref:"Psaume 103:11-12"},
  {text:"Les bontés de l'Éternel ne sont pas épuisées, sa compassion ne s'est pas éteinte. Elle se renouvelle chaque matin. Ta fidélité est grande !",ref:"Lamentations 3:22-23"},
  {text:"Afin que vous soyez capables de comprendre avec tous les saints quelle est la largeur, la longueur, la profondeur et la hauteur, et de connaître l'amour de Christ, qui surpasse toute connaissance.",ref:"Éphésiens 3:18-19"},
  {text:"Comme le Père m'a aimé, je vous ai aussi aimés. Demeurez dans mon amour.",ref:"Jean 15:9"},
  {text:"L'espérance ne trompe point, parce que l'amour de Dieu est répandu dans nos cœurs par le Saint-Esprit qui nous a été donné.",ref:"Romains 5:5"},
  // Amour du prochain
  {text:"Je vous donne un commandement nouveau : Aimez-vous les uns les autres ; comme je vous ai aimés, vous aussi, aimez-vous les uns les autres. À ceci tous connaîtront que vous êtes mes disciples.",ref:"Jean 13:34-35"},
  {text:"L'amour est patient, il est plein de bonté ; l'amour n'est point envieux, il ne se vante point.",ref:"1 Corinthiens 13:4"},
  {text:"Maintenant donc ces trois choses demeurent : la foi, l'espérance, l'amour ; mais la plus grande de ces choses, c'est l'amour.",ref:"1 Corinthiens 13:13"},
  {text:"Mes petits enfants, n'aimons pas en paroles et avec la langue, mais en actions et avec vérité.",ref:"1 Jean 3:18"},
  {text:"Mais moi, je vous dis : Aimez vos ennemis, bénissez ceux qui vous maudissent, faites du bien à ceux qui vous haïssent, et priez pour ceux qui vous maltraitent et qui vous persécutent.",ref:"Matthieu 5:44"},
  {text:"Ce que vous voulez que les hommes fassent pour vous, faites-le de même pour eux.",ref:"Luc 6:31"},
  {text:"Car toute la loi est accomplie dans une seule parole, dans celle-ci : Tu aimeras ton prochain comme toi-même.",ref:"Galates 5:14"},
  {text:"Avant tout, ayez les uns pour les autres une ardente charité, car la charité couvre une multitude de péchés.",ref:"1 Pierre 4:8"},
  {text:"Il n'y a pas de plus grand amour que de donner sa vie pour ses amis.",ref:"Jean 15:13"},
  {text:"Tu aimeras le Seigneur ton Dieu de tout ton cœur, de toute ton âme et de toute ta pensée.",ref:"Matthieu 22:37"},
  {text:"Tu aimeras ton prochain comme toi-même. Je suis l'Éternel.",ref:"Lévitique 19:18"},
  {text:"Louez l'Éternel, car il est bon ! Car sa miséricorde dure à toujours.",ref:"Psaume 136:1"},
  // Prière
  {text:"Notre Père qui es aux cieux ! Que ton nom soit sanctifié ; que ton règne vienne ; que ta volonté soit faite sur la terre comme au ciel. Donne-nous aujourd'hui notre pain quotidien ; pardonne-nous nos offenses.",ref:"Matthieu 6:9-12"},
  {text:"Ne vous inquiétez de rien ; mais en toutes choses faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces.",ref:"Philippiens 4:6"},
  {text:"Soyez toujours joyeux. Priez sans cesse. Rendez grâces en toutes choses, car c'est à votre égard la volonté de Dieu en Jésus-Christ.",ref:"1 Thessaloniciens 5:16-18"},
  {text:"La prière fervente du juste a une grande efficace. Confessez vos péchés les uns aux autres, et priez les uns pour les autres, afin que vous soyez guéris.",ref:"Jacques 5:16"},
  {text:"Si vous demeurez en moi et que mes paroles demeurent en vous, vous demanderez ce que vous voudrez, et cela vous sera accordé.",ref:"Jean 15:7"},
  {text:"Demandez, et l'on vous donnera ; cherchez, et vous trouverez ; frappez, et l'on vous ouvrira.",ref:"Matthieu 7:7"},
  {text:"C'est ici la confiance que nous avons en lui, que si nous demandons quelque chose selon sa volonté, il nous écoute ; et si nous savons qu'il nous écoute, nous savons que nous avons les requêtes que nous lui avons faites.",ref:"1 Jean 5:14-15"},
  {text:"Invoque-moi, et je te répondrai ; je t'annoncerai de grandes choses et des choses cachées, que tu ne connais pas.",ref:"Jérémie 33:3"},
  {text:"Il leur dit encore une parabole, pour montrer qu'il faut toujours prier et ne pas se relâcher.",ref:"Luc 18:1"},
  {text:"De même aussi l'Esprit nous aide dans notre faiblesse, car nous ne savons pas ce qu'il nous convient de demander dans nos prières. Mais l'Esprit lui-même intercède par des soupirs inexprimables.",ref:"Romains 8:26"},
  {text:"Sonde-moi, ô Dieu, et connais mon cœur ! Éprouve-moi et connais mes pensées ! Regarde si je suis sur une mauvaise voie, et conduis-moi sur la voie éternelle !",ref:"Psaume 139:23-24"},
  {text:"J'ai cherché l'Éternel, et il m'a répondu ; il m'a délivré de toutes mes frayeurs.",ref:"Psaume 34:4"},
  {text:"Bénis l'Éternel, ô mon âme ! Que tout ce qui est en moi bénisse son saint nom !",ref:"Psaume 103:1"},
  // Confiance & Paix
  {text:"Ayez confiance en l'Éternel de tout votre cœur, et ne vous appuyez pas sur votre intelligence.",ref:"Proverbes 3:5"},
  {text:"Reconnais-le dans toutes tes voies, et il aplanira tes sentiers.",ref:"Proverbes 3:6"},
  {text:"L'Éternel est mon berger : je ne manquerai de rien.",ref:"Psaume 23:1"},
  {text:"Cherchez premièrement le royaume et la justice de Dieu ; et toutes ces choses vous seront données par-dessus.",ref:"Matthieu 6:33"},
  {text:"Je vous laisse la paix, je vous donne ma paix. Je ne vous donne pas comme le monde donne. Que votre cœur ne se trouble point, et ne se laisse point effrayer.",ref:"Jean 14:27"},
  {text:"Déchargez-vous sur lui de tous vos soucis, car lui-même prend soin de vous.",ref:"1 Pierre 5:7"},
  {text:"Dieu est notre refuge et notre force, un secours qui ne manque jamais dans la détresse.",ref:"Psaume 46:2"},
  {text:"À celui qui est ferme dans ses pensées tu accordes la paix, la paix, parce qu'il se confie en toi.",ref:"Ésaïe 26:3"},
  {text:"Le jour où je crains, moi, je me confie en toi.",ref:"Psaume 56:4"},
  {text:"Si tu te couches, tu seras sans crainte ; tu te coucheras, et ton sommeil sera doux.",ref:"Proverbes 3:24"},
  {text:"Que la paix de Dieu, qui surpasse toute intelligence, garde vos cœurs et vos pensées en Jésus-Christ.",ref:"Philippiens 4:7"},
  {text:"L'Éternel est ma lumière et mon salut : de qui aurais-je crainte ?",ref:"Psaume 27:1"},
  {text:"Car je connais les projets que j'ai formés sur vous : projets de paix et non de malheur, afin de vous donner un avenir et de l'espérance.",ref:"Jérémie 29:11"},
  {text:"Ne crains point, car je suis avec toi ; ne promène pas des regards inquiets, car je suis ton Dieu.",ref:"Ésaïe 41:10"},
  {text:"Celui qui demeure sous l'abri du Très-Haut repose à l'ombre du Tout-Puissant.",ref:"Psaume 91:1"},
  {text:"Je dis de l'Éternel : Il est mon refuge et ma forteresse, mon Dieu en qui je me confie.",ref:"Psaume 91:2"},
  {text:"Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.",ref:"Matthieu 11:28"},
  {text:"L'Éternel te gardera de tout mal ; il gardera ton âme.",ref:"Psaume 121:7"},
  {text:"Réjouissez-vous toujours dans le Seigneur ; je le répète, réjouissez-vous.",ref:"Philippiens 4:4"},
  // Épreuves & Souffrance
  {text:"Toutes choses concourent au bien de ceux qui aiment Dieu, de ceux qui sont appelés selon son dessein.",ref:"Romains 8:28"},
  {text:"Mes frères, regardez comme un sujet de joie complète les diverses épreuves auxquelles vous pouvez vous trouver exposés, sachant que l'épreuve de votre foi produit la patience.",ref:"Jacques 1:2-4"},
  {text:"Car nos légères afflictions du moment présent produisent pour nous, au-delà de toute mesure, un poids éternel de gloire, parce que nous regardons, non point aux choses visibles, mais aux choses invisibles.",ref:"2 Corinthiens 4:17-18"},
  {text:"Aucune tentation ne vous est survenue qui n'ait été humaine, et Dieu est fidèle ; il ne permettra pas que vous soyez tentés au-delà de vos forces ; mais avec la tentation il préparera aussi le moyen d'en sortir.",ref:"1 Corinthiens 10:13"},
  {text:"Le juste a beaucoup de malheurs, mais l'Éternel l'en délivre tous.",ref:"Psaume 34:19"},
  {text:"Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse. Je me glorifierai donc bien plus volontiers dans mes faiblesses, afin que la puissance de Christ repose sur moi.",ref:"2 Corinthiens 12:9"},
  {text:"Car sa colère dure un moment, et sa grâce toute la vie ; le soir arrivent les pleurs, et au matin les cris de joie.",ref:"Psaume 30:5"},
  {text:"Je vous ai dit ces choses afin que vous ayez la paix en moi. Vous aurez des tribulations dans le monde ; mais prenez courage, j'ai vaincu le monde.",ref:"Jean 16:33"},
  {text:"Nous nous glorifions même dans les afflictions, sachant que l'affliction produit la patience, la patience la persévérance, et la persévérance l'espérance. Or l'espérance ne trompe point.",ref:"Romains 5:3-5"},
  {text:"Après que vous aurez souffert un peu de temps, le Dieu de toute grâce, qui vous a appelés en Jésus-Christ à sa gloire éternelle, vous perfectionnera lui-même, vous affermira, vous fortifiera, vous consolidera.",ref:"1 Pierre 5:10"},
  {text:"Je puis tout par celui qui me fortifie.",ref:"Philippiens 4:13"},
  {text:"Mais ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles ; ils courent et ne se lassent point, ils marchent et ne se fatiguent point.",ref:"Ésaïe 40:31"},
  {text:"Il donne de la force à celui qui est fatigué, et il augmente la vigueur de celui qui est sans forces.",ref:"Ésaïe 40:29"},
  {text:"Soyez forts et courageux ! Ne soyez pas effrayés, car l'Éternel ton Dieu est avec toi dans tout ce que tu entreprendras.",ref:"Josué 1:9"},
  {text:"Arrêtez, et sachez que je suis Dieu ! Je serai élevé parmi les nations, je serai élevé sur la terre.",ref:"Psaume 46:10"},
  {text:"Remets ton sort à l'Éternel, mets en lui ta confiance, et il agira.",ref:"Psaume 37:5"},
  // Repentir & Pardon
  {text:"Repentez-vous donc et convertissez-vous, afin que vos péchés soient effacés.",ref:"Actes 3:19"},
  {text:"Si mon peuple, sur qui est invoqué mon nom, s'humilie, prie, et cherche ma face, et s'il se détourne de ses mauvaises voies, je l'exaucerai des cieux, je lui pardonnerai son péché, et je guérirai son pays.",ref:"2 Chroniques 7:14"},
  {text:"Crée en moi un cœur pur, ô Dieu, renouvelle en moi un esprit bien disposé !",ref:"Psaume 51:10"},
  {text:"Si vos péchés sont comme le cramoisi, ils deviendront blancs comme la neige ; s'ils sont rouges comme la pourpre, ils deviendront comme la laine.",ref:"Ésaïe 1:18"},
  {text:"Car si vous pardonnez aux hommes leurs offenses, votre Père céleste vous pardonnera aussi ; mais si vous ne pardonnez pas aux hommes, votre Père ne vous pardonnera pas non plus vos offenses.",ref:"Matthieu 6:14-15"},
  {text:"Supportez-vous les uns les autres, et pardonnez-vous mutuellement si l'un a sujet de se plaindre de l'autre ; comme Christ vous a pardonné, pardonnez-vous aussi.",ref:"Colossiens 3:13"},
  {text:"Quel Dieu est semblable à toi, qui pardonnes l'iniquité ? Il ne garde pas sa colère pour toujours, car il prend plaisir à la grâce. Il jettera tous nos péchés au fond de la mer.",ref:"Michée 7:18-19"},
  {text:"Je vous dis qu'il y aura plus de joie dans le ciel pour un seul pécheur qui se repent, que pour quatre-vingt-dix-neuf justes qui n'ont pas besoin de repentance.",ref:"Luc 15:7"},
  {text:"Soyez bons les uns envers les autres, compatissants, vous pardonnant mutuellement, comme Dieu vous a pardonné en Christ.",ref:"Éphésiens 4:32"},
  {text:"Je ne te dis pas jusqu'à sept fois, mais jusqu'à soixante-dix fois sept fois.",ref:"Matthieu 18:21-22"},
  {text:"L'Éternel passa devant lui et s'écria : L'Éternel, l'Éternel, Dieu compatissant et bienveillant, lent à la colère, riche en bonté et en fidélité !",ref:"Exode 34:6"},
  // Sagesse & Discernement
  {text:"La crainte de l'Éternel est le commencement de la science ; les insensés méprisent la sagesse et l'instruction.",ref:"Proverbes 1:7"},
  {text:"Si quelqu'un d'entre vous manque de sagesse, qu'il la demande à Dieu, qui donne à tous libéralement et sans reproche, et elle lui sera donnée.",ref:"Jacques 1:5"},
  {text:"Garde ton cœur plus que toute autre chose, car de lui viennent les sources de la vie.",ref:"Proverbes 4:23"},
  {text:"Ta parole est une lampe à mes pieds, et une lumière sur mon sentier.",ref:"Psaume 119:105"},
  {text:"Le cœur de l'homme médite sa voie, mais c'est l'Éternel qui dirige ses pas.",ref:"Proverbes 16:9"},
  {text:"Ne vous conformez pas au siècle présent, mais soyez transformés par le renouvellement de l'intelligence, afin que vous discerniez quelle est la volonté de Dieu, ce qui est bon, agréable et parfait.",ref:"Romains 12:2"},
  {text:"Bien-aimés, n'ajoutez pas foi à tout esprit ; mais éprouvez les esprits, pour savoir s'ils sont de Dieu.",ref:"1 Jean 4:1"},
  {text:"Le fer aiguise le fer, et un homme aiguise un autre homme.",ref:"Proverbes 27:17"},
  {text:"Prenez garde que personne ne fasse de vous sa proie par la philosophie et par une vaine tromperie, s'appuyant sur la tradition des hommes, sur les principes élémentaires du monde, et non sur Christ.",ref:"Colossiens 2:8"},
  {text:"La nourriture solide est pour ceux qui sont avancés en âge, pour ceux qui, par l'habitude, ont les sens exercés à discerner le bien et le mal.",ref:"Hébreux 5:14"},
  {text:"Ne sois pas sage à tes propres yeux ; crains l'Éternel, et détourne-toi du mal.",ref:"Proverbes 3:7"},
  {text:"On t'a fait connaître, ô homme, ce qui est bien ; et ce que l'Éternel demande de toi, c'est que tu pratiques la justice, que tu aimes la miséricorde, et que tu marches humblement avec ton Dieu.",ref:"Michée 6:8"},
  // Saint-Esprit
  {text:"Mais vous recevrez une puissance, le Saint-Esprit survenant sur vous, et vous serez mes témoins jusqu'aux extrémités de la terre.",ref:"Actes 1:8"},
  {text:"Mais le consolateur, l'Esprit-Saint, que le Père enverra en mon nom, vous enseignera toutes choses, et vous rappellera tout ce que je vous ai dit.",ref:"Jean 14:26"},
  {text:"Quand le consolateur sera venu, l'Esprit de vérité, il vous conduira dans toute la vérité.",ref:"Jean 16:13"},
  {text:"Mais le fruit de l'Esprit, c'est l'amour, la joie, la paix, la patience, la bonté, la bénignité, la fidélité, la douceur, la tempérance.",ref:"Galates 5:22-23"},
  {text:"Il y a diversité de dons, mais le même Esprit.",ref:"1 Corinthiens 12:4"},
  {text:"Car tous ceux qui sont conduits par l'Esprit de Dieu sont fils de Dieu.",ref:"Romains 8:14"},
  {text:"Ne vous enivrez pas de vin, car le vin mène à la débauche ; soyez au contraire remplis de l'Esprit.",ref:"Éphésiens 5:18"},
  {text:"Repentez-vous, et que chacun de vous soit baptisé au nom de Jésus-Christ, pour le pardon de vos péchés ; et vous recevrez le don du Saint-Esprit.",ref:"Actes 2:38"},
  {text:"Ne savez-vous pas que votre corps est le temple du Saint-Esprit qui est en vous, que vous avez reçu de Dieu, et que vous ne vous appartenez pas ?",ref:"1 Corinthiens 6:19"},
  {text:"Or, le Seigneur c'est l'Esprit ; et là où est l'Esprit du Seigneur, là est la liberté.",ref:"2 Corinthiens 3:17"},
  {text:"Et moi, je prierai le Père, et il vous donnera un autre consolateur, afin qu'il demeure éternellement avec vous.",ref:"Jean 14:16"},
  {text:"Marchez selon l'Esprit et vous n'accomplirez pas les désirs de la chair.",ref:"Galates 5:16"},
  // Espérance & Vie éternelle
  {text:"Moi, je suis la résurrection et la vie. Celui qui croit en moi vivra, quand même il serait mort.",ref:"Jean 11:25"},
  {text:"Il essuiera toute larme de leurs yeux, et la mort ne sera plus, et il n'y aura plus ni deuil, ni cri, ni douleur, car les premières choses ont disparu.",ref:"Apocalypse 21:4"},
  {text:"Car le Seigneur lui-même descendra du ciel avec un cri de commandement, et les morts en Christ ressusciteront premièrement. Ensuite, nous les vivants, nous serons tous ensemble enlevés avec eux dans les airs, et ainsi nous serons toujours avec le Seigneur.",ref:"1 Thessaloniciens 4:16-17"},
  {text:"Je leur donne la vie éternelle, et elles ne périront jamais, et personne ne les ravira de ma main.",ref:"Jean 10:28"},
  {text:"Que le Dieu de l'espérance vous remplisse de toute joie et de toute paix dans la foi, pour que vous abondiez en espérance, par la puissance du Saint-Esprit !",ref:"Romains 15:13"},
  {text:"Béni soit Dieu qui nous a régénérés pour une espérance vivante, par la résurrection de Jésus-Christ d'entre les morts, pour un héritage qui ne peut ni se corrompre, ni se souiller, ni se flétrir, réservé dans les cieux pour vous.",ref:"1 Pierre 1:3-4"},
  {text:"Mais notre citoyenneté est dans les cieux, d'où nous attendons aussi comme sauveur le Seigneur Jésus-Christ, qui transformera le corps de notre humiliation, en le rendant semblable au corps de sa gloire.",ref:"Philippiens 3:20-21"},
  {text:"Car nous savons que si notre maison terrestre, qui n'est qu'une tente, est détruite, nous avons un édifice qui vient de Dieu, une maison éternelle dans les cieux, qui n'est point faite de main d'homme.",ref:"2 Corinthiens 5:1"},
  {text:"Ô mort, où est ta victoire ? Ô mort, où est ton aiguillon ?",ref:"1 Corinthiens 15:55"},
  {text:"Fais de l'Éternel tes délices, et il te donnera ce que ton cœur désire.",ref:"Psaume 37:4"},
  // Louange & Adoration
  {text:"Poussez vers l'Éternel des cris de joie, vous toutes les contrées de la terre ! Servez l'Éternel avec joie, venez en sa présence avec des chants d'allégresse !",ref:"Psaume 100:1-2"},
  {text:"Que tout ce qui respire loue l'Éternel ! Louez l'Éternel !",ref:"Psaume 150:6"},
  {text:"Mais l'heure vient, et elle est déjà venue, où les vrais adorateurs adoreront le Père en esprit et en vérité ; car ce sont là les adorateurs que le Père demande. Dieu est Esprit, et il faut que ceux qui l'adorent l'adorent en esprit et en vérité.",ref:"Jean 4:23-24"},
  {text:"Je bénirai l'Éternel en tout temps ; sa louange sera toujours dans ma bouche.",ref:"Psaume 34:2"},
  {text:"Offrons donc sans cesse à Dieu, par lui, un sacrifice de louanges, c'est-à-dire le fruit de lèvres qui célèbrent son nom.",ref:"Hébreux 13:15"},
  {text:"Venez ! prosternons-nous et humilions-nous, fléchissons le genou devant l'Éternel, notre créateur !",ref:"Psaume 95:6"},
  {text:"Que la parole de Christ habite parmi vous abondamment ; instruisez-vous et exhortez-vous les uns les autres en toute sagesse, par des psaumes, par des hymnes, et par des cantiques spirituels, chantant à Dieu dans vos cœurs avec reconnaissance.",ref:"Colossiens 3:16"},
  {text:"Et toi, tu es saint, toi qui habites au milieu des louanges d'Israël.",ref:"Psaume 22:3"},
  {text:"Vers le milieu de la nuit, Paul et Silas priaient et chantaient les louanges de Dieu, et les prisonniers les écoutaient.",ref:"Actes 16:25"},
  {text:"Ô Éternel, notre Seigneur ! Que ton nom est magnifique sur toute la terre !",ref:"Psaume 8:2"},
  {text:"Les cieux racontent la gloire de Dieu, et l'étendue manifeste l'œuvre de ses mains.",ref:"Psaume 19:2"},
  {text:"L'Éternel est maître de la terre et de tout ce qu'elle renferme, du monde et de ceux qui l'habitent.",ref:"Psaume 24:1"},
  {text:"Saint, saint, saint est l'Éternel des armées ! Toute la terre est pleine de sa gloire !",ref:"Ésaïe 6:3"},
  {text:"Car c'est de lui, et par lui, et pour lui que sont toutes choses. À lui la gloire dans tous les siècles !",ref:"Romains 11:36"},
  {text:"Réjouissez-vous en espérance. Soyez patients dans la tribulation. Persévérez dans la prière.",ref:"Romains 12:12"},
  // Obéissance & Sanctification
  {text:"Si vous m'aimez, gardez mes commandements.",ref:"Jean 14:15"},
  {text:"Je vous exhorte donc, frères, par les compassions de Dieu, à offrir vos corps comme un sacrifice vivant, saint, agréable à Dieu, ce qui sera de votre part un culte raisonnable.",ref:"Romains 12:1"},
  {text:"Mais, puisque celui qui vous a appelés est saint, vous aussi soyez saints dans toute votre conduite, selon qu'il est écrit : Vous serez saints, car je suis saint.",ref:"1 Pierre 1:15-16"},
  {text:"Ce que Dieu veut, c'est votre sanctification.",ref:"1 Thessaloniciens 4:3"},
  {text:"Mettez en pratique la parole, et ne vous bornez pas à l'écouter, en vous trompant vous-mêmes par de faux raisonnements.",ref:"Jacques 1:22"},
  {text:"C'est pourquoi, quiconque entend ces paroles que je dis et les met en pratique, sera semblable à un homme prudent qui a bâti sa maison sur le roc.",ref:"Matthieu 7:24-25"},
  {text:"Rejetons tout fardeau, et le péché qui nous enveloppe si facilement, et courons avec persévérance dans la carrière qui nous est ouverte, ayant les yeux sur Jésus, le chef et le consommateur de la foi.",ref:"Hébreux 12:1-2"},
  {text:"L'obéissance vaut mieux que les sacrifices, et l'observation de sa parole vaut mieux que la graisse des béliers.",ref:"1 Samuel 15:22"},
  {text:"Affectionnez-vous aux choses d'en haut, et non à celles qui sont sur la terre.",ref:"Colossiens 3:2"},
  {text:"Si vous vous mettez en colère, ne péchez point ; que le soleil ne se couche pas sur votre colère.",ref:"Éphésiens 4:26"},
  // Parole de Dieu
  {text:"Toute l'Écriture est inspirée de Dieu et utile pour enseigner, pour convaincre, pour corriger, pour instruire dans la justice.",ref:"2 Timothée 3:16"},
  {text:"L'homme ne vivra pas de pain seulement, mais de toute parole qui sort de la bouche de Dieu.",ref:"Matthieu 4:4"},
  {text:"Au commencement était la Parole, et la Parole était avec Dieu, et la Parole était Dieu.",ref:"Jean 1:1"},
  {text:"Et la Parole a été faite chair, et elle a habité parmi nous, pleine de grâce et de vérité.",ref:"Jean 1:14"},
  {text:"Il est le reflet de sa gloire et l'empreinte de sa personne, et il soutient toutes choses par sa parole puissante.",ref:"Hébreux 1:3"},
  // Mission & Évangélisation
  {text:"Allez, faites de toutes les nations des disciples, les baptisant au nom du Père, du Fils et du Saint-Esprit.",ref:"Matthieu 28:19"},
  {text:"Il leur dit : Allez par tout le monde, et prêchez la bonne nouvelle à toute la création.",ref:"Marc 16:15"},
  {text:"Car je n'ai point honte de l'Évangile de Christ ; c'est une puissance de Dieu pour le salut de quiconque croit.",ref:"Romains 1:16"},
  {text:"Comment invoqueront-ils celui en qui ils n'ont pas cru ? Et comment croiront-ils en celui dont ils n'ont pas entendu parler ? Et comment y aura-t-il des prédicateurs, s'ils ne sont pas envoyés ?",ref:"Romains 10:14-15"},
  {text:"Étant toujours prêts à vous défendre devant quiconque vous demande raison de l'espérance qui est en vous, mais avec douceur et respect.",ref:"1 Pierre 3:15"},
  {text:"Que votre lumière luise ainsi devant les hommes, afin qu'ils voient vos bonnes œuvres et glorifient votre Père.",ref:"Matthieu 5:16"},
  {text:"Prêche la parole, insiste en toute occasion, favorable ou non, reprends, censure, exhorte, avec toute douceur et en instruisant.",ref:"2 Timothée 4:2"},
  {text:"J'entendis la voix du Seigneur, disant : Qui enverrai-je, et qui marchera pour nous ? Je répondis : Me voici, envoie-moi.",ref:"Ésaïe 6:8"},
  {text:"La moisson est grande, mais il y a peu d'ouvriers. Priez donc le maître de la moisson d'envoyer des ouvriers dans sa moisson.",ref:"Matthieu 9:37-38"},
  {text:"Heureux les artisans de paix, car ils seront appelés fils de Dieu.",ref:"Matthieu 5:9"},
  {text:"Car là où deux ou trois sont assemblés en mon nom, je suis au milieu d'eux.",ref:"Matthieu 18:20"},
  // Église & Communion fraternelle
  {text:"Ils persévéraient dans l'enseignement des apôtres, dans la communion des frères, dans la fraction du pain et dans les prières.",ref:"Actes 2:42"},
  {text:"Veillons les uns sur les autres pour nous exciter à la charité et aux bonnes œuvres. N'abandonnons pas notre assemblée, mais exhortons-nous mutuellement.",ref:"Hébreux 10:24-25"},
  {text:"Car, comme le corps est un et a plusieurs membres, et comme tous les membres du corps, malgré leur nombre, ne forment qu'un seul corps, ainsi en est-il de Christ.",ref:"1 Corinthiens 12:12-14"},
  {text:"Il a donné les uns comme apôtres, les autres comme prophètes, les autres comme évangélistes, les autres comme pasteurs et docteurs, pour le perfectionnement des saints en vue de l'œuvre du ministère.",ref:"Éphésiens 4:11-13"},
  {text:"En toute humilité et douceur, avec patience, vous vous supportant les uns les autres avec charité, vous efforçant de conserver l'unité de l'Esprit par le lien de la paix.",ref:"Éphésiens 4:2-3"},
  {text:"Car, comme nous avons plusieurs membres dans un seul corps, et que tous les membres n'ont pas la même fonction, ainsi nous qui sommes plusieurs, nous formons un seul corps en Christ.",ref:"Romains 12:4-5"},
  {text:"Vous, au contraire, vous êtes une race élue, un sacerdoce royal, une nation sainte, un peuple acquis, afin que vous annonciez les vertus de celui qui vous a appelés des ténèbres à son admirable lumière.",ref:"1 Pierre 2:9"},
  {text:"Portez les fardeaux les uns des autres, et vous accomplirez ainsi la loi de Christ.",ref:"Galates 6:2"},
  {text:"La multitude de ceux qui avaient cru était d'un seul cœur et d'une seule âme.",ref:"Actes 4:32"},
  {text:"Affectionnez-vous les uns aux autres avec amour fraternel ; rivalisez d'estime entre vous.",ref:"Romains 12:10"},
  {text:"Nous qui sommes forts, nous devons supporter les faiblesses de ceux qui ne le sont pas, et ne pas nous faire plaisir à nous-mêmes.",ref:"Romains 15:1"},
  // Combat spirituel
  {text:"Revêtez-vous de toutes les armes de Dieu, afin de pouvoir tenir ferme contre les ruses du diable.",ref:"Éphésiens 6:11"},
  {text:"Car nous n'avons pas à lutter contre la chair et le sang, mais contre les dominations, contre les autorités, contre les princes des ténèbres de ce siècle-ci, contre les esprits méchants dans les lieux célestes.",ref:"Éphésiens 6:12"},
  {text:"Soumettez-vous donc à Dieu ; résistez au diable, et il fuira loin de vous.",ref:"Jacques 4:7"},
  {text:"Soyez sobres et veillez. Votre adversaire, le diable, rôde comme un lion rugissant, cherchant quelqu'un à dévorer. Résistez-lui avec une foi ferme.",ref:"1 Pierre 5:8-9"},
  {text:"Car les armes avec lesquelles nous combattons ne sont pas charnelles ; mais elles sont puissantes, par la vertu de Dieu, pour renverser des forteresses.",ref:"2 Corinthiens 10:4-5"},
  {text:"Vous, petits enfants, vous êtes de Dieu, et vous les avez vaincus, parce que celui qui est en vous est plus grand que celui qui est dans le monde.",ref:"1 Jean 4:4"},
  {text:"Voici, je vous ai donné le pouvoir de marcher sur les serpents et les scorpions, et sur toute la puissance de l'ennemi ; et rien ne pourra vous nuire.",ref:"Luc 10:19"},
  {text:"Aucune arme forgée contre toi ne prospérera, et tu condamneras toute langue qui s'élèvera en jugement contre toi.",ref:"Ésaïe 54:17"},
  {text:"Dans toutes ces choses nous sommes plus que vainqueurs par celui qui nous a aimés.",ref:"Romains 8:37"},
  {text:"Ils l'ont vaincu à cause du sang de l'agneau et à cause de la parole de leur témoignage, et ils n'ont pas aimé leur vie jusqu'à craindre la mort.",ref:"Apocalypse 12:11"},
  // Guérison, délivrance & provision
  {text:"Mais il était blessé pour nos péchés, brisé pour nos iniquités ; le châtiment qui nous donne la paix est tombé sur lui, et c'est par ses meurtrissures que nous sommes guéris.",ref:"Ésaïe 53:5"},
  {text:"Quelqu'un parmi vous est-il malade ? Qu'il appelle les anciens de l'Église, et que les anciens prient pour lui, en l'oignant d'huile au nom du Seigneur ; la prière de la foi sauvera le malade.",ref:"Jacques 5:14-15"},
  {text:"Mon âme, bénis l'Éternel, et n'oublie aucun de ses bienfaits ! C'est lui qui pardonne toutes tes iniquités, qui guérit toutes tes maladies.",ref:"Psaume 103:2-3"},
  {text:"Car je suis l'Éternel, qui te guéris.",ref:"Exode 15:26"},
  {text:"D'une parole il chassa les esprits, et il guérit tous les malades, afin que s'accomplit ce qui avait été annoncé : Il a pris nos infirmités, et il s'est chargé de nos maladies.",ref:"Matthieu 8:16-17"},
  {text:"Car je te rendrai la santé, et je guérirai tes plaies, dit l'Éternel.",ref:"Jérémie 30:17"},
  {text:"Ma fille, ta foi t'a sauvée ; va en paix et sois guérie de ton mal.",ref:"Marc 5:34"},
  {text:"Les lionceaux éprouvent la misère et la faim, mais ceux qui cherchent l'Éternel ne manquent d'aucun bien.",ref:"Psaume 34:10"},
  {text:"Et mon Dieu pourvoira à tous vos besoins selon sa richesse, avec gloire, en Jésus-Christ.",ref:"Philippiens 4:19"},
  // Famille, mariage & enfants
  {text:"C'est pourquoi l'homme quittera son père et sa mère, et s'attachera à sa femme, et ils deviendront une seule chair.",ref:"Genèse 2:24"},
  {text:"Maris, aimez vos femmes, comme Christ a aimé l'Église, et s'est livré lui-même pour elle.",ref:"Éphésiens 5:25"},
  {text:"Femmes, soyez soumises à vos maris, comme au Seigneur ; car le mari est le chef de la femme, comme Christ est le chef de l'Église.",ref:"Éphésiens 5:22-23"},
  {text:"Enfants, obéissez à vos parents, selon le Seigneur, car cela est juste. Honore ton père et ta mère — c'est le premier commandement avec une promesse — afin que tu sois heureux et que tu vives longtemps sur la terre.",ref:"Éphésiens 6:1-3"},
  {text:"Et vous, pères, n'irritez pas vos enfants, mais élevez-les en les corrigeant et en les instruisant selon le Seigneur.",ref:"Éphésiens 6:4"},
  {text:"Instruis l'enfant dans la voie qu'il doit tenir ; et quand il sera vieux, il ne s'en détournera pas.",ref:"Proverbes 22:6"},
  {text:"Ces commandements que je te donne aujourd'hui seront dans ton cœur. Tu les inculqueras à tes enfants, et tu en parleras quand tu seras dans ta maison, quand tu iras en voyage, quand tu te coucheras et quand tu te lèveras.",ref:"Deutéronome 6:6-7"},
  {text:"Pour moi et pour ma maison, nous servirons l'Éternel.",ref:"Josué 24:15"},
  {text:"Voici, des fils sont un héritage de l'Éternel ; le fruit des entrailles est une récompense.",ref:"Psaume 127:3"},
  {text:"Femmes, soyez soumises à vos maris, car cela est convenable dans le Seigneur. Maris, aimez vos femmes. Enfants, obéissez en toutes choses à vos parents. Pères, n'irritez pas vos enfants, de peur qu'ils ne se découragent.",ref:"Colossiens 3:18-21"},
  {text:"Je te loue de ce que je suis une créature si merveilleuse. Tes œuvres sont admirables.",ref:"Psaume 139:14"},
  // Travail, argent & générosité
  {text:"Quoi que vous fassiez, faites-le de bon cœur, comme pour le Seigneur et non pour des hommes.",ref:"Colossiens 3:23"},
  {text:"Honore l'Éternel avec tes biens et avec les prémices de tout ton revenu ; alors tes greniers seront remplis d'abondance.",ref:"Proverbes 3:9-10"},
  {text:"Éprouvez-moi donc en cela, dit l'Éternel des armées. Verrez si je n'ouvrirai pas pour vous les écluses des cieux, si je ne répandrai pas sur vous la bénédiction en abondance.",ref:"Malachie 3:10"},
  {text:"Celui qui sème peu moissonnera peu, et celui qui sème abondamment moissonnera abondamment. Que chacun donne comme il l'a résolu en son cœur, sans tristesse ni contrainte ; car Dieu aime celui qui donne avec joie.",ref:"2 Corinthiens 9:6-7"},
  {text:"Ne vous amassez pas des trésors sur la terre ; mais amassez-vous des trésors dans le ciel. Car là où est ton trésor, là aussi sera ton cœur.",ref:"Matthieu 6:19-21"},
  {text:"Car l'amour de l'argent est une racine de tous les maux ; et quelques-uns, en étant possédés, se sont égarés loin de la foi.",ref:"1 Timothée 6:10"},
  {text:"Donnez, et il vous sera donné : on versera dans votre sein une bonne mesure, serrée, secouée et qui déborde ; car on vous mesurera avec la mesure dont vous vous serez servi.",ref:"Luc 6:38"},
  {text:"La fortune acquise à la hâte diminue, mais celui qui amasse peu à peu l'augmente.",ref:"Proverbes 13:11"},
  {text:"Il y a plus de bonheur à donner qu'à recevoir.",ref:"Actes 20:35"},
  // Fin des temps & Retour de Christ
  {text:"Pour ce qui est de ce jour et de cette heure, personne ne le sait, ni les anges des cieux, ni le Fils, mais le Père seul.",ref:"Matthieu 24:36"},
  {text:"Veillez donc, puisque vous ne savez pas quel jour votre Seigneur doit venir.",ref:"Matthieu 24:42"},
  {text:"Ce Jésus, qui a été enlevé au ciel du milieu de vous, viendra de la même manière que vous l'avez vu aller au ciel.",ref:"Actes 1:11"},
  {text:"Car vous savez bien vous-mêmes que le jour du Seigneur viendra comme un voleur dans la nuit.",ref:"1 Thessaloniciens 5:2"},
  {text:"Voici, je viens bientôt, et ma rétribution est avec moi, pour rendre à chacun selon ce qu'est son œuvre.",ref:"Apocalypse 22:12"},
  {text:"Le Seigneur ne tarde pas dans l'accomplissement de sa promesse ; mais il use de patience envers vous, ne voulant pas qu'aucun périsse, mais voulant que tous arrivent à la repentance.",ref:"2 Pierre 3:9"},
  {text:"Cette bonne nouvelle du royaume sera prêchée dans le monde entier, pour servir de témoignage à toutes les nations. Alors viendra la fin.",ref:"Matthieu 24:14"},
  {text:"Puis je vis un nouveau ciel et une nouvelle terre ; car le premier ciel et la première terre avaient disparu, et la mer n'était plus.",ref:"Apocalypse 21:1"},
  {text:"Il y a plusieurs demeures dans la maison de mon Père. Je vais vous préparer une place. Et lorsque je m'en serai allé, je reviendrai et je vous prendrai avec moi, afin que là où je suis, vous y soyez aussi.",ref:"Jean 14:2-3"},
  // Fondements & Majesté
  {text:"Au commencement, Dieu créa les cieux et la terre.",ref:"Genèse 1:1"},
  {text:"Écoute, Israël ! L'Éternel, notre Dieu, est le seul Éternel.",ref:"Deutéronome 6:4"},
  {text:"Car mes pensées ne sont pas vos pensées, et vos voies ne sont pas mes voies, dit l'Éternel. Autant les cieux sont élevés au-dessus de la terre, autant mes voies sont élevées au-dessus de vos voies.",ref:"Ésaïe 55:8-9"},
  // Identité en Christ
  {text:"J'ai été crucifié avec Christ ; et si je vis, ce n'est plus moi qui vis, c'est Christ qui vit en moi ; si je vis maintenant dans la chair, je vis dans la foi au Fils de Dieu, qui m'a aimé et qui s'est livré lui-même pour moi.",ref:"Galates 2:20"},
  {text:"Car nous sommes son ouvrage, ayant été créés en Jésus-Christ pour de bonnes œuvres.",ref:"Éphésiens 2:10"},
  {text:"Il est l'image du Dieu invisible, le premier-né de toute la création.",ref:"Colossiens 1:15"},
  {text:"Ayez en vous les sentiments qui étaient en Jésus-Christ : lui qui, existant en forme de Dieu, s'est dépouillé lui-même en prenant une forme de serviteur, en devenant semblable aux hommes.",ref:"Philippiens 2:5-7"},
  {text:"Car nous n'avons pas un souverain sacrificateur qui ne puisse compatir à nos faiblesses ; au contraire, il a été tenté comme nous en toutes choses, sans commettre de péché.",ref:"Hébreux 4:15"},
  {text:"Que tout homme soit prompt à écouter, lent à parler, lent à se mettre en colère.",ref:"Jacques 1:19"},
  {text:"Tout ce que vous voulez que les hommes fassent pour vous, faites-le de même pour eux, car c'est la loi et les prophètes.",ref:"Matthieu 7:12"},
  {text:"Quiconque invoquera le nom du Seigneur sera sauvé.",ref:"Romains 10:13"},
  {text:"Aimez vos ennemis, faites du bien et prêtez sans rien espérer en retour. Votre récompense sera grande, et vous serez fils du Très-Haut.",ref:"Luc 6:35"},
  {text:"Je suis venu afin que les brebis aient la vie, et qu'elles l'aient en abondance.",ref:"Jean 10:10"},
  {text:"Sonde-moi, ô Dieu, et connais mon cœur ! Éprouve-moi et connais mes pensées !",ref:"Psaume 139:23-24"},
];

// ── Définition des thèmes ────────────────────────────────────────────────────

export interface VerseTheme {
  id:    string;
  label: string;
  emoji: string;
}

export const VERSE_THEMES: VerseTheme[] = [
  { id:"foi",             label:"La foi",                        emoji:"🙏" },
  { id:"esperance",       label:"L'espérance",                   emoji:"🌅" },
  { id:"priere",          label:"La prière",                     emoji:"🕊️" },
  { id:"paix",            label:"La paix",                       emoji:"☮️" },
  { id:"joie",            label:"La joie",                       emoji:"😊" },
  { id:"famille",         label:"La famille & mariage",          emoji:"👨‍👩‍👧" },
  { id:"enfants",         label:"Les enfants",                   emoji:"👶" },
  { id:"amour",           label:"L'amour",                       emoji:"❤️" },
  { id:"amour-dieu",      label:"L'amour de Dieu",               emoji:"💖" },
  { id:"amour-prochain",  label:"L'amour du prochain",           emoji:"🤝" },
  { id:"salut",           label:"La grâce & le salut",           emoji:"✝️" },
  { id:"identite-christ", label:"L'identité en Christ",          emoji:"⭐" },
  { id:"parole",          label:"La Parole de Dieu",             emoji:"📖" },
  { id:"louange",         label:"La louange",                    emoji:"🎵" },
  { id:"mission",         label:"La mission",                    emoji:"🌍" },
  { id:"sagesse",         label:"La sagesse",                    emoji:"💡" },
  { id:"saint-esprit",    label:"Le Saint-Esprit",               emoji:"🔥" },
  { id:"pardon",          label:"Le pardon",                     emoji:"🤍" },
  { id:"repentir",        label:"Le repentir",                   emoji:"🙇" },
  { id:"obeissance",      label:"L'obéissance",                  emoji:"🎯" },
  { id:"eglise",          label:"L'Église & communion",          emoji:"⛪" },
  { id:"combat",          label:"Le combat spirituel",           emoji:"🛡️" },
  { id:"guerison",        label:"Guérison & provision",          emoji:"🏥" },
  { id:"travail",         label:"Le travail & la diligence",     emoji:"💪" },
  { id:"argent",          label:"L'argent & la générosité",      emoji:"🌱" },
  { id:"epreuves",        label:"Les épreuves",                  emoji:"⚓" },
  { id:"fin-temps",       label:"Le retour de Christ",           emoji:"✨" },
];

// ── Versets par thème (références) ──────────────────────────────────────────

const VERSE_REFS_BY_THEME: Record<string, string[]> = {
  foi: [
    "Hébreux 11:1","Hébreux 11:6","Marc 11:22-23","Matthieu 17:20",
    "2 Corinthiens 5:7","Romains 10:17","Jacques 2:17","Éphésiens 6:16",
    "1 Pierre 1:7","Galates 2:20","Marc 9:23","Jacques 1:5",
    "Proverbes 3:5","Jean 14:6","Jean 15:7",
  ],
  esperance: [
    "Jérémie 29:11","Psaume 37:4","Romains 8:28","Philippiens 4:13",
    "Psaume 27:1","Psaume 121:7","Psaume 46:2","Romains 8:38-39",
    "Ésaïe 41:10","Apocalypse 21:4","Lamentations 3:22-23",
    "Romains 15:13","1 Pierre 1:3-4","Romains 5:5","Jean 14:27",
    "1 Corinthiens 15:55","Ésaïe 40:31","Psaume 91:1","Psaume 91:2",
  ],
  priere: [
    "Matthieu 6:9-12","Philippiens 4:6","1 Thessaloniciens 5:16-18",
    "Jacques 5:16","Jean 15:7","Matthieu 7:7","1 Jean 5:14-15",
    "Jérémie 33:3","Luc 18:1","Romains 8:26","Psaume 139:23-24",
    "Psaume 34:4","Psaume 103:1","1 Jean 1:9","Jacques 1:5",
  ],
  paix: [
    "Philippiens 4:7","Jean 14:27","Ésaïe 41:10","Psaume 46:2",
    "Matthieu 11:28","1 Pierre 5:7","Philippiens 4:4","Jean 16:33",
    "Ésaïe 26:3","Matthieu 5:9","Psaume 23:1","Psaume 27:1",
    "Josué 1:9","Philippiens 4:6","Psaume 56:4","Proverbes 3:24",
  ],
  joie: [
    "Philippiens 4:4","1 Thessaloniciens 5:16-18","Psaume 103:1",
    "Psaume 37:4","Romains 12:12","Psaume 136:1","Psaume 8:2",
    "Psaume 100:1-2","Psaume 150:6","Psaume 34:2","Romains 15:13",
    "Actes 16:25","Luc 15:7","Jean 10:10","Lamentations 3:22-23",
    "Psaume 30:5",
  ],
  famille: [
    "Genèse 2:24","Éphésiens 5:25","Éphésiens 5:22-23","Éphésiens 6:1-3",
    "Éphésiens 6:4","Proverbes 22:6","Deutéronome 6:6-7","Josué 24:15",
    "Psaume 127:3","Colossiens 3:18-21","Proverbes 3:5","Proverbes 4:23",
    "Josué 1:9","Romains 12:10","1 Corinthiens 13:4","1 Corinthiens 13:13",
  ],
  enfants: [
    "Psaume 127:3","Psaume 139:14","Deutéronome 6:6-7","Proverbes 22:6",
    "Éphésiens 6:1-3","Éphésiens 6:4","Josué 24:15","Matthieu 11:28",
    "Psaume 23:1","Proverbes 3:5","Deutéronome 6:4","Jean 10:10",
    "Éphésiens 2:10","Psaume 91:1","1 Jean 4:19",
  ],
  amour: [
    "Jean 3:16","1 Jean 4:8","1 Jean 4:19","Romains 5:8","Jean 15:13",
    "Lamentations 3:22-23","Psaume 136:1","1 Corinthiens 13:4",
    "1 Corinthiens 13:13","Jean 13:34-35","Matthieu 22:37",
    "Lévitique 19:18","Jean 10:10","Romains 8:38-39",
  ],
  "amour-dieu": [
    "1 Jean 4:8","Jean 3:16","1 Jean 4:19","Romains 5:8","Jérémie 31:3",
    "Sophonie 3:17","Psaume 103:11-12","Lamentations 3:22-23",
    "Éphésiens 3:18-19","Jean 15:9","Romains 5:5","Romains 8:38-39",
    "Exode 34:6","Psaume 136:1","Jean 15:13",
  ],
  "amour-prochain": [
    "Jean 13:34-35","1 Jean 3:18","Matthieu 5:44","Luc 6:31",
    "Galates 5:14","1 Pierre 4:8","Lévitique 19:18","Matthieu 22:37",
    "Jean 15:13","Romains 12:10","1 Corinthiens 13:4","1 Corinthiens 13:13",
    "Luc 6:35","Éphésiens 4:32","Romains 15:1",
  ],
  salut: [
    "Jean 3:16","Éphésiens 2:8","Romains 10:9","Romains 6:23",
    "Actes 4:12","Tite 3:5","2 Corinthiens 5:17","Romains 5:8",
    "1 Jean 1:9","Jean 14:6","Apocalypse 3:20","Jean 11:25",
    "Jean 10:28","Hébreux 4:15","Ésaïe 53:5","Actes 3:19",
  ],
  "identite-christ": [
    "Galates 2:20","2 Corinthiens 5:17","Jean 10:10","Éphésiens 2:10",
    "Colossiens 1:15","Romains 12:1","Romains 12:2","Éphésiens 6:11",
    "Colossiens 3:2","Galates 5:22-23","Galates 5:16","Psaume 139:14",
    "Philippiens 2:5-7","Jean 14:6","Jean 11:25","Hébreux 12:1-2",
  ],
  parole: [
    "Psaume 119:105","Matthieu 4:4","2 Timothée 3:16","Jacques 1:22",
    "Hébreux 11:1","Romains 10:17","Jean 14:6","Jean 1:1","Jean 1:14",
    "Hébreux 1:3","Proverbes 3:5","Jean 4:23-24","2 Timothée 4:2",
    "Matthieu 7:24-25",
  ],
  louange: [
    "Psaume 100:1-2","Psaume 150:6","Jean 4:23-24","Psaume 34:2",
    "Hébreux 13:15","Psaume 95:6","Colossiens 3:16","Psaume 22:3",
    "Actes 16:25","Psaume 103:1","Psaume 8:2","Psaume 19:2",
    "Psaume 24:1","Ésaïe 6:3","Romains 11:36","Psaume 136:1","Psaume 37:4",
  ],
  mission: [
    "Matthieu 28:19","Marc 16:15","Romains 1:16","Romains 10:14-15",
    "1 Pierre 3:15","Matthieu 5:16","2 Timothée 4:2","Ésaïe 6:8",
    "Matthieu 9:37-38","Actes 1:8","Actes 2:42","Jean 3:16",
    "Actes 4:12","Matthieu 18:20","Matthieu 5:9","Michée 6:8",
  ],
  sagesse: [
    "Proverbes 1:7","Jacques 1:5","Proverbes 4:23","Psaume 119:105",
    "Proverbes 16:9","Romains 12:2","1 Jean 4:1","Proverbes 27:17",
    "Colossiens 2:8","Hébreux 5:14","Proverbes 3:7","Michée 6:8",
    "Jacques 1:19","Proverbes 3:5","Ésaïe 55:8-9",
  ],
  "saint-esprit": [
    "Actes 1:8","Jean 14:26","Jean 16:13","Galates 5:22-23",
    "1 Corinthiens 12:4","Romains 8:14","Éphésiens 5:18","Actes 2:38",
    "1 Corinthiens 6:19","2 Corinthiens 3:17","Jean 14:16","Galates 5:16",
    "Romains 8:26","Romains 15:13","Romains 5:5",
  ],
  pardon: [
    "1 Jean 1:9","Romains 5:8","Ésaïe 53:5","Romains 6:23",
    "Tite 3:5","Apocalypse 3:20","Exode 34:6","Jean 3:16",
    "Psaume 103:1","Lamentations 3:22-23","Hébreux 4:15",
    "2 Corinthiens 5:17","Galates 2:20","Éphésiens 4:32","Colossiens 3:13",
  ],
  repentir: [
    "Actes 3:19","2 Chroniques 7:14","Psaume 51:10","Ésaïe 1:18",
    "Matthieu 6:14-15","Colossiens 3:13","Michée 7:18-19","Luc 15:7",
    "Éphésiens 4:32","Matthieu 18:21-22","1 Jean 1:9","Exode 34:6",
    "Jean 3:16","Apocalypse 3:20",
  ],
  obeissance: [
    "Jean 14:15","Romains 12:1","1 Pierre 1:15-16","1 Thessaloniciens 4:3",
    "Jacques 1:22","Matthieu 7:24-25","Hébreux 12:1-2","Galates 5:16",
    "1 Samuel 15:22","Michée 6:8","Josué 1:9","Jean 14:6",
    "Colossiens 3:2","Romains 12:2",
  ],
  eglise: [
    "Actes 2:42","Hébreux 10:24-25","1 Corinthiens 12:12-14",
    "Éphésiens 4:11-13","Matthieu 18:20","Éphésiens 4:2-3",
    "Romains 12:4-5","1 Pierre 2:9","Galates 6:2","Actes 4:32",
    "Romains 12:10","Galates 5:14","Romains 15:1","Jean 13:34-35",
  ],
  combat: [
    "Éphésiens 6:11","Éphésiens 6:12","Jacques 4:7","1 Pierre 5:8-9",
    "2 Corinthiens 10:4-5","1 Jean 4:4","Luc 10:19","Ésaïe 54:17",
    "Romains 8:37","Apocalypse 12:11","Josué 1:9","Philippiens 4:13",
    "Romains 8:28","Jean 16:33",
  ],
  guerison: [
    "Ésaïe 53:5","Jacques 5:14-15","Psaume 103:2-3","Exode 15:26",
    "Matthieu 8:16-17","Jérémie 30:17","Marc 5:34","Psaume 34:10",
    "Philippiens 4:19","Philippiens 4:13","Psaume 91:1","Psaume 91:2",
    "Jérémie 33:3","Psaume 34:4",
  ],
  travail: [
    "Colossiens 3:23","Proverbes 3:9-10","Actes 20:35","1 Samuel 15:22",
    "Matthieu 5:16","Philippiens 4:13","Éphésiens 2:10","Josué 1:9",
    "Proverbes 3:6","Matthieu 6:33","Romains 12:1","Proverbes 4:23",
    "Galates 5:22-23","Michée 6:8",
  ],
  argent: [
    "Matthieu 6:19-21","Matthieu 6:33","Luc 6:38","2 Corinthiens 9:6-7",
    "Malachie 3:10","Proverbes 3:9-10","1 Timothée 6:10","Philippiens 4:19",
    "Proverbes 13:11","Actes 20:35","Luc 6:35","Psaume 37:4",
  ],
  epreuves: [
    "Romains 8:28","Jacques 1:2-4","2 Corinthiens 4:17-18","1 Corinthiens 10:13",
    "Psaume 34:19","2 Corinthiens 12:9","Psaume 30:5","Jean 16:33",
    "Romains 5:3-5","1 Pierre 5:10","Philippiens 4:13","Ésaïe 41:10",
    "Psaume 46:2","Psaume 46:10","Psaume 27:1","Hébreux 4:15",
    "1 Pierre 5:7","Romains 8:38-39","Lamentations 3:22-23",
    "Ésaïe 40:31","Ésaïe 40:29","Josué 1:9","Matthieu 11:28",
  ],
  "fin-temps": [
    "Matthieu 24:36","Matthieu 24:42","Actes 1:11","1 Thessaloniciens 5:2",
    "Apocalypse 22:12","2 Pierre 3:9","Matthieu 24:14","Apocalypse 21:1",
    "Jean 14:2-3","1 Thessaloniciens 4:16-17","Philippiens 3:20-21",
    "2 Corinthiens 5:1","1 Corinthiens 15:55","Apocalypse 21:4",
  ],
};

// Index rapide pour lookup par référence
const VERSE_BY_REF: Record<string, typeof DAILY_VERSES[0]> = {};
for (const v of DAILY_VERSES) VERSE_BY_REF[v.ref] = v;

// Dictionnaire thème → versets
export const THEMED_VERSES: Record<string, typeof DAILY_VERSES> = {};
for (const [theme, refs] of Object.entries(VERSE_REFS_BY_THEME)) {
  THEMED_VERSES[theme] = refs.map(r => VERSE_BY_REF[r]).filter(Boolean);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function dayIndex(interval: "24" | "48"): number {
  const now = new Date();
  const doy = Math.floor((now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / 86400000);
  return interval === "48" ? Math.floor(doy / 2) : doy;
}

export function getAutoVerset(interval: "24" | "48" = "24") {
  const idx = dayIndex(interval) % DAILY_VERSES.length;
  return DAILY_VERSES[idx];
}

export function getThemedVerset(theme: string, intervalHours: number = 24) {
  const verses = THEMED_VERSES[theme];
  if (!verses || verses.length === 0) return getAutoVerset();
  const h = Math.max(1, Math.min(24, Math.round(intervalHours)));
  const idx = Math.floor(Date.now() / (3600000 * h)) % verses.length;
  return verses[idx];
}
